export { default as Main } from './Main/Main';
export { default as Navbar } from './Nav/Navbar';
export { default as About } from './About/About';
export { default as Certificate } from './Certificate/Certificate';
export { default as Experience } from './Experience/Experience';
export { default as Education } from './Education/Education';
export { default as Skills } from './Skills/Skills';
export { default as Backend } from './Projects/backend/Backend';
export { default as Frontend } from './Projects/frontend/Frontend';
